title: Juno Documentation
description: Official documentation for Juno
url: "https://juno-labs.github.io"
baseurl: "/Juno-Docs"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - getting-started.md
  - configuration.md
  - api-reference.md
  - troubleshooting.md

# Social links
github_username: juno-labs

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections for organized docs
collections:
  guides:
    output: true
    permalink: /:collection/:name/
  api:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "api"